image: haskell:latest

before_script:
  - rm -rf /root/.cabal || true
  - tar -xzf cabal.tar.gz -C / || true
  - cabal new-update
  - cabal new-build

after_script:
  - tar -czf cabal.tar.gz /root/.cabal || true

cache:
  paths:
    - dist/
    - dist-newstyle/
    - cabal.tar.gz

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - cabal new-exec site rebuild
  except:
    - master

pages:
  stage: deploy
  script:
    - cabal new-exec site build
  artifacts:
    paths:
      - public
  only:
    - master
